import { ScorePlayer, StandaloneMetronome } from './audio.js';
import { VoiceTracker, pitchVerdict } from './pitch.js';
import { expectedNoteAt } from './timeline.js';
import { correctNote, correctMeasure, addNote, removeNote, validateScore } from './corrections.js';
import { library, scoreId } from './storage.js';
import { submitRecognition } from './recognition-client.js';
import { renderPdfPage } from './renderer.js';
import * as pdfjs from './vendor/pdf.mjs';
import { upgradeSample } from './sample-upgrade.js';
import { pageWindow, changePart, enterRhythm, leaveRhythm } from './state.js';
import { scoreForPages } from './public-score.js';
pdfjs.GlobalWorkerOptions.workerSrc = './vendor/pdf.worker.mjs';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const icons = {
  play:'<path d="m8 5 11 7-11 7Z"/>',pause:'<path d="M8 5v14M16 5v14"/>',stop:'<rect x="6" y="6" width="12" height="12" rx="1"/>',
  upload:'<path d="M12 16V3m-4 4 4-4 4 4M4 15v5h16v-5"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',
  'chevron-left':'<path d="m14 6-6 6 6 6"/>','chevron-right':'<path d="m10 6 6 6-6 6"/>','arrow-right':'<path d="M4 12h16m-6-6 6 6-6 6"/>',
  close:'<path d="m6 6 12 12M6 18 18 6"/>',rhythm:'<path d="M7 17V5l11-2v12M7 9l11-2"/><ellipse cx="4.5" cy="18" rx="2.5" ry="2"/><ellipse cx="15.5" cy="16" rx="2.5" ry="2"/>',
  loop:'<path d="M19 8a7 7 0 0 0-12-3L4 8m0-4v4h4M5 16a7 7 0 0 0 12 3l3-3m0 4v-4h-4"/>',
  mic:'<rect x="9" y="3" width="6" height="11" rx="3"/><path d="M6 10v2a6 6 0 0 0 12 0v-2M12 18v3m-3 0h6"/>',
  metronome:'<path d="M8 3h8l5 18H3L8 3ZM12 16l6-11M7 17h10"/><circle cx="12" cy="16" r="1"/>',
  info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',expand:'<path d="M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6"/>'
};
function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.info}</svg>`;}
function decorate(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
decorate();
let parts=[['soprano','S'],['alto','A'],['tenor','T'],['bass','B'],['piano','P']];
const names={soprano:'Soprano',alto:'Alto',tenor:'Tenor',bass:'Bass',piano:'Piano'};
const state={mode:'notes',selected:new Set(parts.map(p=>p[0])),saved:new Set(),pdf:null,pages:[],anchor:0,zoom:1,fit:'width',sample:true,playing:false,loop:null,loopPick:0,loopFirst:null,active:null,selection:new Set(),importPdf:null,importFile:null,monitorRunning:false};
let renderGeneration=0,toastTimeout,audio;
let sampleBytes;
let appConfig;
let samples=[];
let currentScore={events:samples,parts:parts.map(([id])=>({id,name:names[id]}))};let noteMap=new Map(samples.map(n=>[String(n.id),n]));let player,metroPlayer,voice;let saveTimer;const traceHistory=[];
function findNote(id){return noteMap.get(String(id));}

function landscape(){return matchMedia('(orientation: landscape)').matches;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('#toast').hidden=true,3300);}
function audioContext(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio;}
function activePages(){return pageWindow(state.anchor,state.pages.length,landscape());}
const renderPage=renderPdfPage;
function staffPositions(page){
 return currentScore.staves?.[page] || [];
}
async function renderScore(){
 if(!state.pdf)return;const generation=++renderGeneration;const visible=activePages();state.anchor=visible[0]||0;
 const stage=$('#score-stage'),spread=$('#page-spread');spread.replaceChildren();
 const maxWidth=(stage.clientWidth-64-(visible.length-1)*30)/visible.length-44;
 const fit=state.fit==='page'?Math.min(maxWidth,(stage.clientHeight-25)/1.414):maxWidth;const width=Math.max(180,fit)*state.zoom;
 for(const logical of visible){const actual=state.pages[logical],shell=document.createElement('article');shell.className='score-sheet';shell.dataset.page=actual;
  const base=(await state.pdf.getPage(actual+1)).getViewport({scale:1});if(generation!==renderGeneration)return;const aspect=base.height/base.width;
  const paper=document.createElement('div');paper.className='paper';paper.style.width=`${width}px`;paper.style.height=`${width*aspect}px`;
  const c=document.createElement('canvas');paper.append(c);shell.append(paper);
  const line=document.createElement('div');line.className='line-parts';line.style.height=`${width*aspect}px`;
  staffPositions(actual).forEach(row=>{const label=document.createElement('label');label.className='part-check';label.style.top=`${row.y*100}%`;label.title=`${names[row.part]} — controls this part everywhere`;const input=document.createElement('input');input.type='checkbox';input.dataset.part=row.part;input.checked=state.selected.has(row.part);input.setAttribute('aria-label',`${names[row.part]}, page ${actual+1}, line ${row.system+1}`);input.onchange=()=>{changePart(state,row.part,input.checked);syncParts();saveSoon();};const short=document.createElement('span');short.textContent=(names[row.part]||row.short).slice(0,1);label.append(input,short);line.append(label);});shell.append(line);
  const layer=document.createElement('div');layer.className='note-layer';paper.append(layer);
  samples.filter(n=>n.page===actual&&n.x!=null&&n.midi!=null).forEach(note=>{const button=document.createElement('button');button.className='note-target';button.style.left=`${note.x*100}%`;button.style.top=`${note.y*100}%`;button.dataset.note=note.id;button.title=`${names[note.part]}, bar ${note.measure}, beat ${note.beat+1}`;button.setAttribute('aria-label',button.title);button.onclick=event=>{if(event.detail===0)return noteTap(note);const box=paper.getBoundingClientRect(),x=(event.clientX-box.left)/box.width,y=(event.clientY-box.top)/box.height;const closest=samples.filter(n=>n.page===actual&&n.x!=null&&n.midi!=null).reduce((best,n)=>Math.hypot((n.x-x)*box.width,(n.y-y)*box.height)<Math.hypot((best.x-x)*box.width,(best.y-y)*box.height)?n:best,note);noteTap(closest);};layer.append(button);});
  const label=document.createElement('span');label.className='sheet-label';label.textContent=actual+1;shell.append(label);spread.append(shell);
  renderPage(state.pdf,actual,c,width).then(()=>c.dataset.ready='true').catch(e=>{if(generation===renderGeneration)toast('This page could not be rendered. Try reopening the PDF.');console.error(e);});
 }
 updatePageLabels();syncParts();paintNotes();$('#zoom-reset').textContent=state.zoom===1?(state.fit==='width'?'Fit width':'Fit page'):`${Math.round(state.zoom*100)}%`;
}
function updatePageLabels(){const visible=activePages(),actual=visible.map(i=>state.pages[i]+1);const label=actual.length===2?`${actual[0]}–${actual[1]}`:`${actual[0]}`;$('#reading-position').textContent=`${actual.length===2?'Pages':'Page'} ${label} of ${state.pdf.numPages}`;$('#page-count').innerHTML=`${visible.map(i=>i+1).join('–')} <span>/ ${state.pages.length}</span>`;$('#previous-page').disabled=state.anchor===0;$('#next-page').disabled=state.anchor+visible.length>=state.pages.length;}
function syncParts(){player?.syncSelection();$$('[data-part]').forEach(c=>c.checked=state.selected.has(c.dataset.part));const count=state.selected.size;$('#mode-label').textContent=state.mode==='rhythm'?(count?`Rhythm · ${names[[...state.selected][0]]}`:'Rhythm · choose one voice'):count===parts.length?'All voices':count===0?'Beat only':count===1?names[[...state.selected][0]]:`${count} parts enabled`;$('#rhythm-button').setAttribute('aria-pressed',state.mode==='rhythm');updateMessage();}
function updateMessage(){const el=$('#mode-message');if(state.loopPick){el.hidden=false;el.innerHTML=`<span>Loop: tap the ${state.loopPick===1?'first':'last'} note</span><button id="cancel-loop">Cancel</button>`;$('#cancel-loop').onclick=clearLoop;}
 else if(state.loop){el.hidden=false;el.innerHTML=`<span>Loop · bars ${state.loop[0].measure}–${state.loop[1].measure}</span><label><input id="loop-count-in" type="checkbox"> Count in each time</label><button id="cancel-loop">Clear</button>`;$('#loop-count-in').checked=!!state.loopCountIn;$('#loop-count-in').onchange=e=>{state.loopCountIn=e.target.checked;if(player?.options)player.options.loopCountIn=state.loopCountIn;saveSoon();};$('#cancel-loop').onclick=clearLoop;}
 else if(state.mode==='rhythm'){el.hidden=false;el.textContent=state.selected.size?'Rhythm practice · your selected voice, with the beat':'Choose one voice using any checkbox beside the score';}
 else el.hidden=true;}
function paintNotes(){$$('[data-note]').forEach(el=>{const n=findNote(el.dataset.note);if(!n)return;el.classList.toggle('active',state.active?.id===n.id);el.classList.toggle('loop-selected',!!state.loop&&n.time>=state.loop[0].time&&n.time<=state.loop[1].time);});}
function shiftPage(dir){state.anchor+=dir;renderScore();$('#score-stage').scrollTop=0;saveSoon();}
function clearLoop(){const wasPlaying=state.playing;const position=player?.position();state.loop=null;state.loopPick=0;state.loopFirst=null;$('#loop-button').setAttribute('aria-pressed','false');paintNotes();updateMessage();saveSoon();if(wasPlaying)playFrom({...state.active,time:position},false);}
function noteTap(note){if(state.loopPick){if(state.loopPick===1){state.loopFirst=note;state.loopPick=2;}else{state.loop=[state.loopFirst,note].sort((a,b)=>a.time-b.time);state.loopPick=0;paintNotes();saveSoon();}updateMessage();return;}state.active=note;if(player)player.paused=null;paintNotes();playFrom(note);}
function ensurePlayer(){if(!player)player=new ScorePlayer(audioContext(),{selection:()=>state.selected,mode:()=>state.mode,onEvent:e=>{
 if(e.kind==='count'){ $('#count-in').hidden=false;$('#count-in strong').textContent=e.beat+1;beatPulse(e.beat%4);return;}
 $('#count-in').hidden=true;if(e.kind==='beat')beatPulse(e.beat%4);
 else{state.active=e.note;paintNotes();$('#target-pitch').textContent=pitchName(e.note.midi);if(e.note.page!=null&&!activePages().some(i=>state.pages[i]===e.note.page)){const index=state.pages.indexOf(e.note.page);if(index>=0){state.anchor=index;renderScore();}}else{const el=$(`[data-note="${e.note.id}"]`);if(el){const bounds=el.getBoundingClientRect(),viewport=$('#score-stage').getBoundingClientRect();if(bounds.top<viewport.top+25||bounds.bottom>viewport.bottom-25)el.scrollIntoView({block:'center',inline:'nearest',behavior:'smooth'});}}}
 },onEnd:()=>{stopPlayback();player.paused=null;state.active=null;paintNotes();}});return player;}
function stopPlayback(){state.playing=false;player?.stop();$('#play-button').innerHTML=icon('play');$('#play-button').setAttribute('aria-label','Play score');$('#count-in').hidden=true;$$('#beat-indicator i').forEach(i=>i.classList.remove('current'));}
function bpm(){return Math.max(30,Math.min(240,+$('#score-bpm').value||92));}
function playFrom(note,countIn=true){stopPlayback();if(!note||!samples.length){toast('Recognise the selected pages before playing.');return;}if(state.mode==='rhythm'&&!state.selected.size){toast('Select one voice beside the score first.');return;}
 const timingErrors=validateScore(currentScore).filter(i=>i.kind==='error');if(timingErrors.length){toast(timingErrors[0].message+' Open Review notes to correct it.');return;}
 if(state.loop&&(note.time<state.loop[0].time||note.time>=state.loop[1].time+state.loop[1].duration))clearLoop();
 const loop=state.loop?{start:state.loop[0].time,end:state.loop[1].time+state.loop[1].duration}:null;ensurePlayer().play(currentScore,note.time,{bpm:bpm(),loop,countIn,loopCountIn:!!state.loopCountIn});state.playing=true;$('#play-button').innerHTML=icon('pause');$('#play-button').setAttribute('aria-label','Pause score');$('#transport-note-text').textContent=currentScore.demo?'Original practice exercise':currentScore.recognition?'Recognised score · check uncertain notes':'PDF viewing only';}

function resumePlayback(){const note=state.loop?.[0]||state.active||samples.find(n=>n.midi!=null)||samples[0];if(player?.paused!=null&&note){playFrom({...note,time:player.paused},!!player.pausedWasCounting);}else playFrom(note);}
function beatPulse(index){$$('#beat-indicator i').forEach((el,i)=>el.classList.toggle('current',i===index));}
function pitchName(midi){return ['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'][midi%12]+(Math.floor(midi/12)-1);}
function toggleDrawer(id,button){const drawer=$(id),willOpen=drawer.hidden;stopVoice();$$('.drawer').forEach(d=>d.hidden=true);$('#metronome-button').setAttribute('aria-expanded','false');$('#monitor-button').setAttribute('aria-pressed','false');drawer.hidden=!willOpen;button.setAttribute(id==='#monitor-drawer'?'aria-pressed':'aria-expanded',willOpen);if(willOpen&&id==='#monitor-drawer')drawTrace(false);}
let metroRunning=false,metroIndex=0;
function setMetro(v){v=Math.max(30,Math.min(240,v));$('#metro-bpm').value=v;$('#metro-bpm-display').textContent=v;if(metroRunning)metroPlayer.start(metroOptions());}
function metroOptions(){return {bpm:+$('#metro-bpm').value,num:+$('#metro-metre').value.split('/')[0],accent:$('#metro-accent').checked,tone:$('#metro-tone').value,volume:+$('#metro-volume').value/100*.30};}
function toggleMetro(){if(!metroPlayer)metroPlayer=new StandaloneMetronome(audioContext(),{onEvent:e=>$$('#metro-beats i').forEach((el,i)=>el.classList.toggle('current',i===e.beat))});metroRunning=!metroRunning;if(metroRunning)metroPlayer.start(metroOptions());else{metroPlayer.stop();$$('#metro-beats i').forEach(i=>i.classList.remove('current'));}$('#metro-start').innerHTML=icon(metroRunning?'stop':'play')+(metroRunning?'Stop metronome':'Start metronome');}

function drawTrace(){const c=$('#pitch-trace'),r=c.getBoundingClientRect();if(!r.width)return;c.width=r.width*2;c.height=r.height*2;const ctx=c.getContext('2d');ctx.scale(2,2);const w=r.width,h=r.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#e3e9da';[.2,.5,.8].forEach(y=>{ctx.beginPath();ctx.moveTo(0,h*y);ctx.lineTo(w,h*y);ctx.stroke();});const values=traceHistory.flatMap(n=>[n.target,n.detected]).filter(n=>n!=null);const center=values.length?values.reduce((a,b)=>a+b,0)/values.length:67;const min=Math.min(center-2,...values),max=Math.max(center+2,...values);const y=n=>h-(n-min)/(max-min)*h;for(const [key,color] of [['target','#acb895'],['detected','#688657']]){ctx.strokeStyle=color;ctx.lineWidth=key==='detected'?2:1;ctx.setLineDash(key==='target'?[4,3]:[]);ctx.beginPath();let connected=false;traceHistory.forEach((n,i)=>{if(n[key]==null){connected=false;return;}const x=i/Math.max(1,traceHistory.length-1)*w;connected?ctx.lineTo(x,y(n[key])):ctx.moveTo(x,y(n[key]));connected=true;});ctx.stroke();}ctx.setLineDash([]);}
function onVoice(detected){const frameTime=detected?.frameTime??audioContext().currentTime;const segment=player?.playing?player.currentSegment(frameTime):null;const pos=player?.playing?player.positionAt(frameTime):state.active?.time;const target=segment&&frameTime<segment.origin?null:pos!=null?expectedNoteAt(currentScore,pos,$('#monitor-part').value):null;const audibleMidi=player?.playing&&state.mode==='notes'?samples.filter(n=>n.midi!=null&&state.selected.has(n.part)&&pos>=n.time-.08&&pos<n.time+n.duration+.08).map(n=>n.midi):[];const verdict=pitchVerdict(detected,target?.midi,{audibleMidi});const label=$('#pitch-verdict');label.className='pitch-verdict'+(verdict.kind==='warn'?' warn':verdict.kind==='bad'?' bad':'');label.textContent=verdict.kind==='neutral'?(verdict.reason==='speaker'?'Speaker overlap · uncertain':target?'Listening · uncertain':'Waiting for a target note'):verdict.kind==='good'?'✓ In tune':`${verdict.direction==='lower'?'↓':'↑'} ${verdict.direction==='lower'?'Sing lower':'Sing higher'}`;$('#target-pitch').textContent=target?pitchName(target.midi):'—';$$('[data-note]').forEach(el=>{el.classList.remove('feedback-good','feedback-warn','feedback-bad');if(target&&el.dataset.note===String(target.id)&&verdict.kind!=='neutral')el.classList.add('feedback-'+verdict.kind);});traceHistory.push({target:target?.midi??null,detected:detected&&detected.clarity>=.90?detected.midi:null});if(traceHistory.length>150)traceHistory.shift();drawTrace();}
function stopVoice(){voice?.stop();state.monitorRunning=false;$('#monitor-demo').innerHTML=icon('mic')+'Start monitoring';$('#pitch-verdict').textContent='Monitoring off';$$('[data-note]').forEach(el=>el.classList.remove('feedback-good','feedback-warn','feedback-bad'));}
async function toggleMonitor(){if(state.monitorRunning){stopVoice();return;}try{voice??=new VoiceTracker(audioContext(),onVoice);$('#monitor-demo').disabled=true;await voice.start();if(!voice.running)return;state.monitorRunning=true;traceHistory.length=0;$('#monitor-demo').innerHTML=icon('stop')+'Stop monitoring';$('#pitch-verdict').textContent='Listening…';}catch(e){toast(e.name==='NotAllowedError'?'Microphone permission was denied. Allow it in your browser settings.':e.message||'Microphone unavailable.');}finally{$('#monitor-demo').disabled=false;}}

async function showImport(pdf=state.pdf,file=null){stopPlayback();state.importPdf=pdf;state.importFile=file;state.selection=new Set(Array.from({length:pdf.numPages},(_,i)=>i));$('#import-filename').textContent=file?.name||state.filename;const grid=$('#thumbnail-grid');grid.replaceChildren();$('#import-dialog').showModal();updateSelection();
 const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){observer.unobserve(entry.target);const canvas=entry.target.querySelector('canvas');renderPage(pdf,+entry.target.dataset.index,canvas,220).catch(()=>{});}}),{root:grid,rootMargin:'100px'});
 for(let i=0;i<pdf.numPages;i++){const card=document.createElement('div');card.className='thumbnail-card';card.dataset.index=i;card.innerHTML=`<button class="thumbnail-select selected" aria-label="Include page ${i+1}" aria-pressed="true"><canvas></canvas><span class="thumb-check">✓</span></button><div class="thumbnail-caption"><span>Page ${i+1}</span><button class="icon-button" aria-label="Enlarge page ${i+1}">${icon('expand')}</button></div>`;
  card.querySelector('.thumbnail-select').onclick=()=>{if(state.selection.has(i))state.selection.delete(i);else state.selection.add(i);updateSelection();};card.querySelector('.thumbnail-caption button').onclick=()=>enlargePage(pdf,i);grid.append(card);observer.observe(card);
 }$('#import-dialog').addEventListener('close',()=>observer.disconnect(),{once:true});
}
function updateSelection(){$('#selection-count').textContent=`${state.selection.size} ${state.selection.size===1?'page':'pages'} selected`;$('[id=import-continue]').disabled=!state.selection.size;$$('.thumbnail-card').forEach(card=>{const selected=state.selection.has(+card.dataset.index),button=card.querySelector('.thumbnail-select');button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',selected);});}
async function enlargePage(pdf,i){const content=$('#page-preview-content');content.replaceChildren();const c=document.createElement('canvas');content.append(c);$('#page-preview-dialog').showModal();await renderPage(pdf,i,c,Math.min(innerWidth*.8,(innerHeight-100)/1.414));}
async function upload(file){if(!file)return;if(file.size>64*1024*1024)return toast('Choose a PDF under 64 MB.');if(file.type!=='application/pdf'&&!/\.pdf$/i.test(file.name))return toast('Choose a PDF score.');try{toast('Opening PDF pages…');const bytes=await file.arrayBuffer();state.pendingBytes=bytes;await saveNow();const pdf=await pdfjs.getDocument({data:bytes.slice(0),isEvalSupported:false}).promise;showImport(pdf,file);}catch(e){toast('Could not open this PDF. Check that it is readable and not password protected.');}}
$('#library-button').onclick=async()=>{await renderLibrary();$('#library-dialog').showModal();};$('#close-library').onclick=()=>$('#library-dialog').close();$('#open-sample').onclick=async()=>{$('#library-dialog').close();await saveNow();await openOriginal();};
$('#upload-button').onclick=()=>$('#pdf-file').click();$('#library-upload').onclick=()=>{$('#library-dialog').close();$('#pdf-file').click();};$('#pdf-file').onchange=e=>{upload(e.target.files[0]);e.target.value='';};
// The original score's page previews are also accessible without choosing a new file.
$('#reading-position').style.cursor='pointer';$('#reading-position').title='Choose included pages';$('#reading-position').setAttribute('aria-label','Choose included pages');$('#reading-position').setAttribute('role','button');$('#reading-position').tabIndex=0;$('#reading-position').onclick=()=>showImport();$('#reading-position').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showImport();}};
$('#select-all').onclick=()=>{state.selection=new Set(Array.from({length:state.importPdf.numPages},(_,i)=>i));updateSelection();};$('#select-none').onclick=()=>{state.selection.clear();updateSelection();};$('#close-import').onclick=()=>$('#import-dialog').close();$('#close-page-preview').onclick=()=>$('#page-preview-dialog').close();
$('#import-continue').onclick=async()=>{if(!state.selection.size)return;const file=state.importFile;const request={pdf:state.importPdf,bytes:file?state.pendingBytes:state.pdfBytes,pages:[...state.selection].sort((a,b)=>a-b),id:file?await scoreId(state.pendingBytes):state.id,filename:file?.name||state.filename,title:file?file.name.replace(/\.pdf$/i,''):$('#score-title').textContent,imported:!!file,resetAnchor:true};$('#import-dialog').close();await recognisePages(request);};

$('#previous-page').onclick=()=>shiftPage(-1);$('#next-page').onclick=()=>shiftPage(1);$('#zoom-out').onclick=()=>{state.zoom=Math.max(1,state.zoom-.2);renderScore();saveSoon();};$('#zoom-in').onclick=()=>{state.zoom=Math.min(4,state.zoom+.2);renderScore();saveSoon();};$('#zoom-reset').onclick=()=>{if(state.zoom!==1)state.zoom=1;else state.fit=state.fit==='width'?'page':'width';renderScore();saveSoon();};
function updateTempo(value){$('#score-bpm').value=Math.max(30,Math.min(240,value));player?.setBpm(bpm());saveSoon();}$('#bpm-down').onclick=()=>updateTempo(bpm()-2);$('#bpm-up').onclick=()=>updateTempo(bpm()+2);$('#score-bpm').onchange=()=>updateTempo(bpm());
$('#play-button').onclick=()=>state.playing?(player.pause(),state.playing=false,$('#play-button').innerHTML=icon('play'),$('#play-button').setAttribute('aria-label','Play score')):resumePlayback();$('#stop-button').onclick=()=>{stopPlayback();if(player)player.paused=null;state.active=null;paintNotes();};
$('#rhythm-button').onclick=()=>{stopPlayback();if(state.mode==='notes')enterRhythm(state);else leaveRhythm(state);syncParts();};$('#loop-button').onclick=()=>{if(state.loop||state.loopPick)clearLoop();else if(!samples.length)toast('Recognise notes before selecting a loop.');else{stopPlayback();state.loopPick=1;$('#loop-button').setAttribute('aria-pressed','true');updateMessage();}};
$('#metronome-button').onclick=()=>toggleDrawer('#metronome-drawer',$('#metronome-button'));$('#monitor-button').onclick=()=>toggleDrawer('#monitor-drawer',$('#monitor-button'));
$$('[data-close]').forEach(b=>b.onclick=()=>{$('#'+b.dataset.close).hidden=true;$('#metronome-button').setAttribute('aria-expanded','false');$('#monitor-button').setAttribute('aria-pressed','false');if(b.dataset.close==='monitor-drawer')stopVoice();});
$('#metro-bpm').oninput=e=>{setMetro(+e.target.value);};$('#metro-minus').onclick=()=>setMetro(+$('#metro-bpm').value-2);$('#metro-plus').onclick=()=>setMetro(+$('#metro-bpm').value+2);$('#metro-start').onclick=toggleMetro;$('#metro-metre').onchange=()=>{metroIndex=0;const n=+$('#metro-metre').value.split('/')[0];$('#metro-beats').innerHTML='<i></i>'.repeat(n);if(metroRunning)metroPlayer.start(metroOptions());};['metro-tone','metro-accent','metro-volume'].forEach(id=>$('#'+id).oninput=()=>{if(metroRunning)metroPlayer.start(metroOptions());});$('#monitor-demo').onclick=toggleMonitor;
let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{renderScore();if(!$('#monitor-drawer').hidden)drawTrace(state.monitorRunning);},150);});
addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||$('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();$('#play-button').click();}if(e.key==='ArrowRight')shiftPage(1);if(e.key==='ArrowLeft')shiftPage(-1);if(e.key==='Escape'){$$('.drawer').forEach(d=>d.hidden=true);stopVoice();$('#metronome-button').setAttribute('aria-expanded','false');$('#monitor-button').setAttribute('aria-pressed','false');}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPlayback();if(metroRunning)toggleMetro();stopVoice();}});
let reviewNote,reviewPage,reviewAdding=false,reviewPlacing=false,reviewRenderGeneration=0;
const reviewUndo=[];
for(let midi=21;midi<=108;midi++)$('#review-pitch').add(new Option(pitchName(midi),midi));
function positionedNotes(page){return samples.filter(n=>n.page===page&&n.x!=null&&n.y!=null);}
function closestHead(event,paper,notes,fallback){
 if(event.detail===0)return fallback;
 const box=paper.getBoundingClientRect(),x=event.clientX-box.left,y=event.clientY-box.top;
 return notes.reduce((best,n)=>Math.hypot(n.x*box.width-x,n.y*box.height-y)<Math.hypot(best.x*box.width-x,best.y*box.height-y)?n:best,fallback);
}
function setReviewBar(number){
 const measure=currentScore.measures.find(m=>m.number===number);if(!measure)return;
 $('#review-bar').value=number;$('#review-metre-num').value=measure.timeSig.num;$('#review-metre-den').value=measure.timeSig.den;$('#review-bar-length').value=measure.duration;
}
function selectReviewNote(note){
 if(!note)return;reviewNote=note;$('#review-note-picker').value=note.id;$('#review-part').value=note.part;$('#review-part-name').value=names[note.part]||note.part;$('#review-pitch').value=note.midi==null?'rest':note.midi;
 if(![...$('#review-duration').options].some(o=>+o.value===note.duration))$('#review-duration').add(new Option(`${note.duration} quarter beats`,note.duration));
 $('#review-duration').value=note.duration;$('#review-onset').value=note.beat;setReviewBar(note.measure);
 $('#review-location').textContent=`Bar ${note.measure} · ${note.midi==null?'rest':pitchName(note.midi)} · ${note.x==null?'unmapped — place this note':note.reviewed?'reviewed':note.uncertain?'flagged for review':'check against print'}`;
 $$('#review-page [data-note]').forEach(el=>el.classList.toggle('active',el.dataset.note===String(note.id)));
}
function reviewReport(message=''){
 const errors=validateScore(currentScore).filter(i=>i.kind==='error');const flagged=samples.filter(n=>n.uncertain).length;
 $('#review-summary').textContent=message||(errors.length?`${errors.length} timing issue(s). ${errors[0].message}`:`${flagged} flagged notes. Check suggested part names and the printed score.`);
 $('#review-undo').disabled=!reviewUndo.length;const warnings=[...(currentScore.warnings||[]),...validateScore(currentScore).filter(i=>i.kind==='warning').map(i=>i.message)];$('#review-warnings').replaceChildren(...[...new Set(warnings)].map(text=>{const li=document.createElement('li');li.textContent=text.includes('MetronomeInter')?'A tempo marking needs review. Use the BPM control for playback.':text;return li;}));$('#review-warning-panel').hidden=!warnings.length;
}
async function showReview(pageOverride,selectedId){
 stopPlayback();stopVoice();if(!samples.length)return toast('Recognise the selected pages first.');
 const pages=state.pages.filter(p=>samples.some(n=>n.page===p));if(!pages.length)pages.push(state.pages[0]);
 const page=Number.isInteger(pageOverride)&&pages.includes(pageOverride)?pageOverride:pages.includes(state.pages[state.anchor])?state.pages[state.anchor]:pages[0];
 reviewPage=page;const inspectable=samples.filter(n=>n.page===page||n.page==null);$('#review-note-picker').replaceChildren(...inspectable.map(n=>new Option(`Bar ${n.measure} · ${names[n.part]} · ${n.midi==null?'rest':pitchName(n.midi)}${n.x==null?' · unmapped':''}`,n.id)));const generation=++reviewRenderGeneration;$('#review-page-picker').replaceChildren(...pages.map(p=>new Option(`Page ${p+1}`,p)));$('#review-page-picker').value=page;
 $('#review-bar').replaceChildren(...currentScore.measures.map(m=>new Option(`Bar ${m.number}`,m.number)));
 if(!$('#review-dialog').open)$('#review-dialog').showModal();reviewReport();
 const box=$('#review-page');box.replaceChildren();const paper=document.createElement('div');paper.className='review-paper';const canvas=document.createElement('canvas');paper.append(canvas);box.append(paper);
 const width=Math.max(180,Math.min(600,box.clientWidth-45));paper.style.width=`${width}px`;
 $$('.review-inspector button,.review-inspector input,.review-inspector select').forEach(el=>el.disabled=true);await renderPage(state.pdf,page,canvas,width);if(generation!==reviewRenderGeneration)return;$$('.review-inspector button,.review-inspector input,.review-inspector select').forEach(el=>el.disabled=false);reviewReport();
 const layer=document.createElement('div');layer.className='note-layer';paper.append(layer);const notes=positionedNotes(page);
 for(const n of notes){const el=document.createElement('button');el.className='note-target'+(n.uncertain?' uncertain':'')+(n.midi==null?' rest':'');el.style.left=`${n.x*100}%`;el.style.top=`${n.y*100}%`;el.dataset.note=n.id;el.setAttribute('aria-label',`Review ${names[n.part]}, bar ${n.measure}, ${n.midi==null?'rest':pitchName(n.midi)}`);el.onclick=event=>{if(reviewAdding||reviewPlacing)return;selectReviewNote(closestHead(event,paper,notes,n));};layer.append(el);}
 paper.onclick=event=>{if(reviewPlacing&&reviewNote){const rect=paper.getBoundingClientRect();const score=structuredClone(currentScore),note=score.events.find(n=>n.id===reviewNote.id);note.page=page;note.x=(event.clientX-rect.left)/rect.width;note.y=(event.clientY-rect.top)/rect.height;note.reviewed=true;note.uncertain=false;setAdding(false);commitScore(score,note.id);return;}if(!reviewAdding)return;const rect=paper.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height;
  try{const score=addNote(currentScore,{id:crypto.randomUUID(),part:$('#review-part').value,midi:$('#review-pitch').value==='rest'?null:+$('#review-pitch').value,measure:+$('#review-bar').value,beat:+$('#review-onset').value,duration:+$('#review-duration').value,page,x,y});commitScore(score,score.events.at(-1).id);setAdding(false);}catch(e){toast(e.message);}
 };
 paper.classList.toggle('adding',reviewAdding||reviewPlacing);selectReviewNote(inspectable.find(n=>n.id===selectedId)||notes[0]||inspectable[0]);
}
function setAdding(value){reviewPlacing=false;$('#review-place').textContent='Place this note';reviewAdding=value;$('#review-add').textContent=value?'Cancel placement':'Add missing note';$('.review-paper')?.classList.toggle('adding',value);if(value)reviewReport('Set the pitch, voice, bar, onset and duration, then tap the printed note.');}
async function commitScore(score,selectedId,remember=true){
 if(remember){reviewUndo.push(currentScore);if(reviewUndo.length>20)reviewUndo.shift();}
 const loopIds=state.loop?.map(n=>n.id);currentScore=score;samples=score.events;noteMap=new Map(samples.map(n=>[String(n.id),n]));
 if(loopIds){state.loop=loopIds.map(findNote);if(state.loop.some(n=>!n))clearLoop();}
 score.parts.forEach(p=>names[p.id]=(p.name==='Voice'?p.suggestedName:p.name)||p.name||p.id);
 for(const id of ['review-part','monitor-part'])for(const option of $('#'+id).options)option.textContent=names[option.value];
 renderScore();await showReview(reviewPage,selectedId);reviewReport('Saving correction…');const saved=await saveNow();if(currentScore===score)reviewReport(saved?'Correction saved on this device.':'Correction applied, but storage is unavailable.');
}
$('#review-button').onclick=()=>{reviewUndo.length=0;setAdding(false);showReview();};$('#review-page-picker').onchange=e=>{setAdding(false);showReview(+e.target.value);};$('#review-part').onchange=e=>$('#review-part-name').value=names[e.target.value]||e.target.value;
$('#review-next-uncertain').onclick=async()=>{const notes=samples.filter(n=>n.uncertain&&(n.page==null||state.pages.includes(n.page)));const next=notes[(notes.indexOf(reviewNote)+1)%notes.length];if(!next)return toast('No flagged notes remain. Check all notes against the print.');setAdding(false);if(next.page!==reviewPage)await showReview(next.page,next.id);selectReviewNote(next);$(`#review-page [data-note="${next.id}"]`)?.scrollIntoView({block:'center'});};
$('#close-review').onclick=$('#finish-review').onclick=()=>{setAdding(false);reviewRenderGeneration++;$('#review-dialog').close();};
$('#apply-correction').onclick=()=>{if(!reviewNote)return;try{const score=correctNote(currentScore,reviewNote.id,{midi:$('#review-pitch').value==='rest'?null:+$('#review-pitch').value,duration:+$('#review-duration').value,beat:+$('#review-onset').value,part:$('#review-part').value});const part=score.parts.find(p=>p.id===score.events.find(n=>n.id===reviewNote.id).part);part.name=$('#review-part-name').value.trim()||part.id;delete part.suggestedName;commitScore(score,reviewNote.id);}catch(e){reviewReport(e.message);toast(e.message);}};
$('#review-note-picker').onchange=e=>selectReviewNote(findNote(e.target.value));$('#review-place').onclick=()=>{const next=!reviewPlacing;setAdding(false);reviewPlacing=next;$('#review-place').textContent=next?'Cancel placement':'Place this note';$('.review-paper')?.classList.toggle('adding',next);if(next)reviewReport('Choose the printed page, then tap this note’s printed position.');};
$('#review-add').onclick=()=>setAdding(!reviewAdding);$('#review-remove').onclick=()=>{if(reviewNote)commitScore(removeNote(currentScore,reviewNote.id));};$('#review-undo').onclick=()=>{if(reviewUndo.length)commitScore(reviewUndo.pop(),reviewNote?.id,false);};
$('#review-bar').onchange=e=>setReviewBar(+e.target.value);
['review-metre-num','review-metre-den'].forEach(id=>$('#'+id).onchange=()=>$('#review-bar-length').value=+$('#review-metre-num').value*4/+$('#review-metre-den').value);
$('#review-apply-bar').onclick=()=>{try{commitScore(correctMeasure(currentScore,+$('#review-bar').value,{num:+$('#review-metre-num').value,den:+$('#review-metre-den').value,duration:+$('#review-bar-length').value}),reviewNote?.id);}catch(e){reviewReport(e.message);toast(e.message);}};
$('#monitor-mute-part').onclick=()=>{changePart(state,$('#monitor-part').value,false);syncParts();saveSoon();};
$('#monitor-part').onchange=()=>{traceHistory.length=0;$('#target-pitch').textContent='—';};
function loadScore(score){reviewUndo.length=0;if(player)player.paused=null;state.active=null;state.loop=null;state.loopPick=0;currentScore=score;samples=score.events||[];noteMap=new Map(samples.map(n=>[String(n.id),n]));parts=score.parts.map(p=>[p.id,((p.name==='Voice'?p.suggestedName:p.name)||p.name||p.id).slice(0,1)]);score.parts.forEach(p=>names[p.id]=(p.name==='Voice'?p.suggestedName:p.name)||p.name||p.id);state.selected=new Set(parts.map(p=>p[0]));state.saved=new Set(state.selected);state.mode='notes';for(const id of ['review-part','monitor-part']){const sel=$('#'+id);sel.replaceChildren();score.parts.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=names[p.id];sel.append(o);});}$('#score-status').textContent=score.demo?'Original exercise · ready to practise':score.recognition?`Recognised ${new Set(score.events.map(n=>n.page)).size} pages · review notes`:appConfig.recognitionAvailable?'PDF ready · recognition needed':'PDF saved · viewing only';$('#preview-badge')?.remove();syncParts();}
async function openOriginal(){stopPlayback();stopVoice();const sample=appConfig.sample;sampleBytes??=await(await fetch(sample.pdf)).arrayBuffer();state.pdfBytes=sampleBytes;state.id=sample.id;state.filename=sample.title+'.pdf';state.sample=false;state.pdf=await pdfjs.getDocument({data:sampleBytes.slice(0),isEvalSupported:false}).promise;state.pages=Array.from({length:state.pdf.numPages},(_,i)=>i);state.anchor=0;$('#score-title').textContent=sample.title;$('#score-subtitle').textContent=sample.subtitle;const stored=await library.get(state.id).catch(()=>null);const response=await fetch(sample.score);const score=upgradeSample(stored?.score,await response.json());loadScore(score);if(stored)restoreSettings(stored);if(!stored){clearLoop();$('#score-bpm').value=sample.bpm||92;}await renderScore();saveSoon();}
function restoreSettings(record){state.pages=record.pages||state.pages;state.anchor=record.anchor||0;state.zoom=record.zoom||1;state.fit=record.fit||'width';state.loopCountIn=!!record.loopCountIn;$('#score-bpm').value=record.bpm||92;state.selected=new Set(record.selected||parts.map(p=>p[0]));if(record.loop){state.loop=record.loop.map(findNote);if(state.loop.some(n=>!n))state.loop=null;}syncParts();paintNotes();}
function scoreRecord(){if(!state.id||!state.pdfBytes)return null;return {id:state.id,title:$('#score-title').textContent,filename:state.filename,bytes:state.pdfBytes,score:currentScore,pages:state.pages,anchor:state.anchor,zoom:state.zoom,fit:state.fit,bpm:bpm(),selected:[...(state.mode==='rhythm'?state.saved:state.selected)],loop:state.loop?.map(n=>n.id)||null,loopCountIn:!!state.loopCountIn};}
async function saveNow(){clearTimeout(saveTimer);const record=scoreRecord();if(!record)return false;try{await library.put(record);if(state.id===record.id)localStorage.setItem('sight-last-score',record.id);return true;}catch{toast('Could not save on this device. Check available browser storage.');return false;}}
function saveSoon(){clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,350);}
async function openSaved(record){stopPlayback();stopVoice();state.pdfBytes=record.bytes;state.id=record.id;state.filename=record.filename;state.sample=false;state.pdf=await pdfjs.getDocument({data:record.bytes.slice(0),isEvalSupported:false}).promise;state.pages=record.pages;state.anchor=0;$('#score-title').textContent=record.title;$('#score-subtitle').textContent='Saved on this device';loadScore(record.score);restoreSettings(record);await renderScore();localStorage.setItem('sight-last-score',record.id);}
async function renderLibrary(){const container=$('#saved-scores');container.replaceChildren();const records=await library.list().catch(()=>[]);for(const record of records){const row=document.createElement('div');row.className='saved-score-row';const open=document.createElement('button');open.className='saved-score-open';open.textContent=record.title;open.onclick=async()=>{$('#library-dialog').close();await saveNow();await openSaved(record);};const remove=document.createElement('button');remove.className='text-button';remove.textContent='Delete';remove.onclick=async()=>{if(confirm('Delete this saved score and its corrections?')){await library.remove(record.id);if(state.id===record.id)state.id=null;renderLibrary();}};row.append(open,remove);container.append(row);}}
let recognitionAbort;
async function recognisePages(request){const target=request||{bytes:state.pdfBytes,pdf:state.pdf,pages:[...state.pages],id:state.id,filename:state.filename,title:$('#score-title').textContent};if(!target.bytes)return;if(!appConfig.recognitionAvailable){if(!request)return toast('Automatic PDF recognition needs the local server. Uploaded PDFs can be viewed and saved here.');stopPlayback();stopVoice();const score=target.imported?{parts:[],events:[],measures:[],staves:{},warnings:[],duration:0}:scoreForPages(currentScore,target.pages);state.pdfBytes=target.bytes;state.pdf=target.pdf;state.id=target.id;state.filename=target.filename;state.pages=target.pages;state.anchor=0;state.zoom=1;if(target.imported){$('#score-title').textContent=target.title;$('#score-subtitle').textContent='PDF viewing · recognition requires the local version';}loadScore(score);await saveNow();await renderScore();return;}$('#recognition-dialog').showModal();$('#recognition-message').textContent='Preparing only the selected pages…';recognitionAbort=new AbortController();try{const score=await submitRecognition(target.bytes,target.pages,{signal:recognitionAbort.signal,onProgress:job=>$('#recognition-message').textContent=job.message});state.pdfBytes=target.bytes;state.pdf=target.pdf;state.id=target.id;state.filename=target.filename;state.pages=target.pages;if(target.resetAnchor){state.anchor=0;state.zoom=1;}if(target.imported){state.sample=false;$('#score-title').textContent=target.title;$('#score-subtitle').textContent='Imported PDF';}loadScore(score);await saveNow();$('#recognition-dialog').close();await renderScore();showReview();}catch(e){$('#recognition-dialog').close();toast(e.name==='AbortError'?'Recognition cancelled. Your previous score is unchanged.':e.message);}}
$('#recognise-button').onclick=()=>recognisePages();$('#cancel-recognition').onclick=()=>recognitionAbort?.abort();$('#recognition-dialog').addEventListener('cancel',()=>recognitionAbort?.abort());
async function init(){try{const response=await fetch('./assets/app-config.json');if(!response.ok)throw new Error('App configuration could not load.');appConfig=await response.json();const sample=appConfig.sample;const card=$('#open-sample');card.querySelector('.library-cover>span').textContent=sample.cover;card.querySelector('div:nth-child(2)>b').textContent=sample.title;card.querySelector('div:nth-child(2)>span').textContent=sample.subtitle;card.querySelector('div:nth-child(2)>small').textContent=sample.description;if(!appConfig.recognitionAvailable){$('#recognise-button').textContent='About PDF import';$('#import-continue').innerHTML='Include selected pages '+icon('arrow-right');$('#import-instruction').textContent='PDFs are saved for viewing. Automatic note recognition requires the local version; the original demo is ready for full practice.';$('#library-privacy').textContent='PDFs, corrections and practice settings stay in this browser. The hosted app does not upload your PDFs or microphone audio.';$('#ipad-local-guide').hidden=true;}const lastId=localStorage.getItem('sight-last-score');const stored=lastId&&lastId!==sample.id?await library.get(lastId):null;if(stored)await openSaved(stored);else await openOriginal();}catch(e){$('#page-spread').innerHTML='<div class="score-loading">The score could not open. Use Add score to choose a PDF.</div>';toast(e.message||'Unable to load the score.');console.error(e);}}
init();
