import test from 'node:test';
import assert from 'node:assert/strict';
import {ScorePlayer,StandaloneMetronome} from '../audio.js';
const score={parts:[{id:'S',name:'Soprano'}],measures:[{number:1,start:0,duration:4,timeSig:{num:4,den:4}}],events:[{id:'a',part:'S',midi:69,time:0,duration:1,measure:1,beat:0},{id:'b',part:'S',midi:71,time:1,duration:1,measure:1,beat:1}]};
function context(){const nodes=[];return {currentTime:0,destination:{},nodes,resume(){},createGain(){return {connect(){},gain:{value:1,setValueAtTime(){},exponentialRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(value){this.value=value}}}},createOscillator(){const n={frequency:{value:0},connect(){},start(t){this.started=t},stop(t){this.stopped=t??0}};nodes.push(n);return n;}};}
function player(ctx,selection=()=>new Set(['S'])){const p=new ScorePlayer(ctx,{selection});return p;}
test('loop starts at the exact previous boundary with no scheduling gap',()=>{const ctx=context(),p=player(ctx);try{p.play(score,0,{bpm:60,countIn:false,loop:{start:0,end:1}});ctx.currentTime=.95;p.pump();const tones=ctx.nodes.filter(n=>n.frequency.value===440);assert.equal(tones.length,2);assert.ok(Math.abs(tones[1].started-tones[0].started-1)<1e-9);assert.ok(Math.abs(p.position()-.895)<1e-9);ctx.currentTime=1.065;assert.ok(Math.abs(p.position()-.01)<1e-9);}finally{p.stop();}});
test('pause stops scheduled sound and retains its exact musical position',()=>{const ctx=context(),p=player(ctx);p.play(score,0,{bpm:120,countIn:false});ctx.currentTime=.305;p.pause();assert.equal(p.playing,false);assert.ok(Math.abs(p.paused-.5)<1e-9);assert.ok(ctx.nodes.every(n=>n.stopped===0));assert.equal(p.visuals.size,0);});
test('live tempo changes cannot carry the previous count-in option into loop cycles',()=>{const ctx=context(),p=player(ctx);try{p.play(score,0,{bpm:60,countIn:false,loop:{start:0,end:2},loopCountIn:true});ctx.currentTime=.3;p.setBpm(120);assert.equal(p.bpm,120);assert.equal(p.options.countIn,false);assert.equal(p.options.loopCountIn,true);assert.equal(p.options.bpm,120);}finally{p.stop();}});
test('short loops cannot queue hundreds of obsolete visual segments',()=>{const ctx=context(),p=player(ctx);try{p.play(score,0,{bpm:240,countIn:false,loop:{start:0,end:.25}});ctx.currentTime=.24;p.pump();assert.ok(p.segments.length<10);assert.ok(p.position()>=0&&p.position()<.25);}finally{p.stop();}});
test('metronome schedules independent accented beats at its own tempo',()=>{const ctx=context(),p=new StandaloneMetronome(ctx);try{p.start({bpm:120,num:3,accent:true,tone:'bright',volume:.2});ctx.currentTime=.48;p.pump();assert.deepEqual(ctx.nodes.map(n=>n.frequency.value),[1900,1200]);assert.ok(Math.abs(ctx.nodes[1].started-ctx.nodes[0].started-.5)<1e-9);}finally{p.stop();}});
test('muted sustained parts can be enabled and muted immediately without restarting transport',()=>{const ctx=context();let selected=new Set();const p=player(ctx,()=>selected);try{p.play(score,0,{bpm:60,countIn:false});assert.ok(ctx.nodes.some(n=>n.frequency.value===440),'muted note must still be scheduled behind its part gain');const bus=p.partGains.get('S');assert.equal(bus.gain.value,0);selected=new Set(['S']);p.syncSelection();assert.equal(bus.gain.value,1);const origin=p.origin;selected.clear();p.syncSelection();assert.equal(bus.gain.value,0);assert.equal(p.origin,origin);assert.equal(p.playing,true);}finally{p.stop();}});
test('tempo changes during count-in restart a complete musical count instead of skipping it',()=>{const ctx=context(),p=player(ctx);try{p.play(score,0,{bpm:60,countIn:true});ctx.currentTime=1.1;p.setBpm(120);assert.equal(p.counting,true);assert.equal(p.plan.filter(e=>e.kind==='count').length,4);assert.ok(Math.abs(p.origin-p.base-2)<1e-9);}finally{p.stop();}});
test('pause remembers that the count was in progress',()=>{const ctx=context(),p=player(ctx);p.play(score,0,{bpm:60,countIn:true});ctx.currentTime=1.1;p.pause();assert.equal(p.pausedWasCounting,true);assert.equal(p.paused,0);});
