const {chromium}=require('./browser-runtime.cjs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const page=await browser.newPage({viewport:{width:1380,height:1024},deviceScaleFactor:2});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173');await page.waitForFunction(()=>document.querySelectorAll('.paper canvas').length===2&&[...document.querySelectorAll('.paper canvas')].every(c=>c.dataset.ready==='true'));
 await page.locator('#review-button').click();await page.locator('#review-page canvas[data-ready=true]').waitFor();await page.getByRole('button',{name:/^Review Soprano/}).first().press('Enter');
 const originalCount=await page.locator('#review-page [data-note]').count();const onset=await page.locator('#review-onset').inputValue(),duration=await page.locator('#review-duration').inputValue();
 await page.locator('#review-onset').fill('4');await page.locator('#apply-correction').click();await page.waitForFunction(()=>document.querySelector('#review-summary').textContent.includes('beyond bar'));await page.locator('#review-onset').fill(onset);
 await page.locator('#review-add').click();await page.locator('#review-onset').fill('0');await page.locator('#review-pitch').selectOption('rest');await page.locator('#review-duration').selectOption('0.25');await page.locator('.review-paper').click({position:{x:45,y:180}});
 const saved=()=>page.waitForFunction(()=>document.querySelector('#review-summary').textContent==='Correction saved on this device.');await saved();assert.equal(await page.locator('#review-page [data-note]').count(),originalCount+1);assert.equal(await page.locator('#review-pitch').inputValue(),'rest');
 await page.locator('#review-remove').click();await saved();assert.equal(await page.locator('#review-page [data-note]').count(),originalCount);await page.locator('#review-undo').click();await saved();assert.equal(await page.locator('#review-page [data-note]').count(),originalCount+1);await page.locator('#review-undo').click();await saved();assert.equal(await page.locator('#review-page [data-note]').count(),originalCount);
 await page.locator('.bar-editor summary').click();await page.locator('#review-bar').selectOption('1');await page.locator('#review-metre-num').fill('5');await page.locator('#review-metre-num').dispatchEvent('change');await page.locator('#review-apply-bar').click();await saved();
 const read=()=>page.evaluate(async()=>{const {library}=await import('/storage.js');const score=(await library.get('united-in-purpose')).score;return {num:score.measures[0].timeSig.num,nextStart:score.measures[1].start,duration:score.duration};});assert.deepEqual(await read(),{num:5,nextStart:5,duration:313});await page.locator('#review-undo').click();await saved();assert.deepEqual(await read(),{num:4,nextStart:4,duration:312});
 await page.screenshot({path:'screenshots/development-review.png'});await page.locator('#finish-review').click();await page.locator('#loop-button').click();await page.locator('[data-note][title^="Soprano"]').first().press('Enter');await page.locator('[data-note][title^="Soprano"]').nth(3).press('Enter');await page.locator('#play-button').click();await page.waitForTimeout(800);await page.locator('#play-button').click();assert.equal(await page.locator('#play-button').getAttribute('aria-label'),'Play score');await page.locator('#play-button').click();assert.equal(await page.locator('#play-button').getAttribute('aria-label'),'Pause score');await page.locator('#cancel-loop').click();assert.equal(await page.locator('#play-button').getAttribute('aria-label'),'Pause score');await page.locator('#stop-button').click();
 await page.locator('#library-button').click();await page.locator('#library-dialog[open]').waitFor();assert.ok(await page.locator('.saved-score-open').count()>0);await page.locator('#close-library').click();await page.reload();await page.waitForFunction(()=>document.querySelector('.paper canvas')?.dataset.ready==='true');assert.deepEqual(await read(),{num:4,nextStart:4,duration:312});assert.deepEqual(errors,[]);console.log('PASS: edit validation, missing rest placement, deletion, undo, metre reflow and persistence, keyboard note targeting, loop pause/resume and live clear.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
