const {chromium,webkit}=require('./browser-runtime.cjs');
const assert=require('node:assert/strict');
(async()=>{
 const engine=process.env.BROWSER==='webkit'?webkit:chromium;const browser=await engine.launch(engine===webkit?{headless:true}:{headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
 try{
 const page=await browser.newPage({viewport:{width:1180,height:820},deviceScaleFactor:2});const errors=[];page.on('requestfailed',r=>console.error('REQUEST FAILED:',r.url(),r.failure()?.errorText));page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR:',e.stack)});page.on('console',m=>{if(m.type()==='error')console.error('BROWSER:',m.text())});
 const tapHead=async locator=>{await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox();await page.mouse.click(b.x+b.width/2,b.y+b.height/2);};
 const ready=()=>page.waitForFunction(()=>document.querySelector('.paper canvas')&&[...document.querySelectorAll('.paper canvas')].every(c=>c.dataset.ready==='true'));
 console.log('Opening score');await page.goto('http://localhost:5173');await ready();console.log('Score ready');assert.equal(await page.locator('.score-sheet').count(),2);
 assert.ok(await page.locator('.paper canvas').first().evaluate(c=>c.width/c.getBoundingClientRect().width)>=2.9);
 await page.screenshot({path:'screenshots/development-landscape.png'});
 await page.locator('#next-page').click();await ready();assert.equal(await page.locator('.score-sheet').first().getAttribute('data-page'),'1');assert.equal(await page.locator('.score-sheet').last().getAttribute('data-page'),'2');
 await page.locator('[data-part="P1"]').first().uncheck();assert.equal(await page.locator('[data-part="P1"]:checked').count(),0);
 await page.locator('#rhythm-button').click();assert.equal(await page.locator('[data-part]:checked').count(),0);await page.locator('[data-part="P2"]').first().check();await page.locator('[data-part="P3"]').first().check();assert.deepEqual(await page.locator('[data-part]:checked').evaluateAll(cs=>[...new Set(cs.map(c=>c.dataset.part))]),['P3']);await page.locator('#rhythm-button').click();assert.equal(await page.locator('[data-part="P1"]:checked').count(),0);
 await page.locator('#loop-button').click();await tapHead(page.locator('[data-note][title^="Soprano"]').first());await tapHead(page.locator('[data-note][title^="Soprano"]').nth(3));assert.match(await page.locator('[data-note][title^="Soprano"]').nth(3).getAttribute('class'),/loop-selected/);assert.ok(!(await page.locator('[data-note][title^="Soprano"]').nth(4).getAttribute('class')).includes('loop-selected'));assert.match(await page.locator('#mode-message').textContent(),/Loop · bars/);await page.locator('#loop-count-in').check();await page.locator('#cancel-loop').click();
 console.log('Review and persistence');await page.locator('#review-button').click();await page.locator('#review-page-picker').selectOption('2');await page.waitForFunction(()=>document.querySelector('#review-page canvas')?.dataset.ready==='true');await page.locator('#review-next-uncertain').click();await page.locator('#review-page canvas[data-ready=true]').waitFor();await page.waitForFunction(()=>!document.querySelector('#review-part').disabled);await page.locator('#review-part').selectOption('P1');await page.locator('#review-part-name').fill('Soprano verified');await page.locator('#review-pitch').selectOption('69');await page.locator('#apply-correction').click();await page.waitForFunction(()=>document.querySelector('#review-summary').textContent==='Correction saved on this device.');await page.locator('#finish-review').click();await ready();await page.waitForTimeout(900);
 await page.reload();await ready();assert.equal(await page.locator('[data-part="P1"]:checked').count(),0);await page.locator('#monitor-button').click();assert.match(await page.locator('#monitor-part option[value="P1"]').textContent(),/Soprano verified/);if(!process.env.SKIP_MIC){await page.locator('#monitor-demo').click();await page.getByRole('button',{name:'Stop monitoring',exact:true}).waitFor();await page.waitForTimeout(400);}await page.screenshot({path:'screenshots/development-monitor.png'});await page.getByRole('button',{name:'Close voice monitor',exact:true}).click();assert.match(await page.locator('#monitor-demo').textContent(),/Start monitoring/);
 await page.locator('#metronome-button').click();await page.locator('#metro-start').click();await page.waitForFunction(()=>document.querySelector('#metro-beats i.current'));await page.locator('#metro-start').click();await page.getByRole('button',{name:'Close metronome',exact:true}).click();
 await page.setViewportSize({width:820,height:1180});await page.waitForTimeout(300);await ready();assert.equal(await page.locator('.score-sheet').count(),1);await page.screenshot({path:'screenshots/development-portrait.png'});
 assert.equal((await page.request.get('http://localhost:5173/%2Eruntime/tessdata/eng.traineddata')).status(),404);
 console.log(`PASS: ${process.env.BROWSER||'Chrome'} sharp rendering, orientations, overlapping page turns, linked parts, rhythm restoration, loop selection, persisted corrections, metronome, hidden runtime protection. Microphone lifecycle ${process.env.SKIP_MIC?'skipped':'passed with synthetic device'}.`);
 if(process.env.TEST_RECOGNITION==='1'){
 await page.locator('#pdf-file').setInputFiles('assets/united-in-purpose.pdf');await page.locator('#import-dialog[open]').waitFor();await page.locator('#select-none').click();for(const n of [1,2,3])await page.getByRole('button',{name:`Include page ${n}`,exact:true}).click();
 await page.locator('#import-continue').click();await page.locator('#recognition-dialog[open]').waitFor();console.log('Processing actual selected-page browser upload…');const timer=setInterval(async()=>console.log(await page.locator('#recognition-message').textContent().catch(()=>'')),20000);
 try{await page.locator('#review-dialog[open]').waitFor({timeout:240000});}finally{clearInterval(timer);}
 assert.match(await page.locator('#score-status').textContent(),/Recognised 3 pages/);assert.equal(await page.locator('#review-part option').count(),5);await page.locator('#finish-review').click();await ready();assert.equal(await page.locator('.score-sheet').first().getAttribute('data-page'),'0');assert.ok(await page.locator('[data-note]').count()>100);console.log('PASS: real PDF upload → selected-page extraction → local Audiveris job → five parts → mapped notes → correction review.');
 }
 assert.deepEqual(errors,[]);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
