const {chromium}=require('./browser-runtime.cjs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});try{
 const page=await browser.newPage({viewport:{width:1180,height:820},deviceScaleFactor:2});const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).pathname.includes('/api/'))api.push(r.url());});page.on('requestfailed',r=>console.error('REQUEST FAILED:',r.url(),r.failure()?.errorText));
 const url=process.env.SIGHT_TEST_URL||'http://127.0.0.1:4189/sight./';await page.goto(url);const ready=()=>page.waitForFunction(()=>document.querySelectorAll('.paper canvas').length>0&&[...document.querySelectorAll('.paper canvas')].every(c=>c.dataset.ready==='true'));await ready();assert.equal(await page.locator('#score-title').textContent(),'Morning Practice');assert.equal(await page.locator('.score-sheet').count(),2);assert.ok(await page.locator('[data-note]').count()>100);await page.screenshot({path:'screenshots/public-landscape.png'});
 await page.locator('#next-page').click();await ready();assert.equal(await page.locator('.score-sheet').first().getAttribute('data-page'),'1');assert.equal(await page.locator('.score-sheet').last().getAttribute('data-page'),'2');await page.locator('[data-part="P1"]').first().uncheck();assert.equal(await page.locator('[data-part="P1"]:checked').count(),0);await page.locator('#rhythm-button').click();assert.equal(await page.locator('[data-part]:checked').count(),0);await page.locator('[data-part="P2"]').first().check();await page.locator('#rhythm-button').click();assert.equal(await page.locator('[data-part="P1"]:checked').count(),0);
 await page.locator('#play-button').click();assert.equal(await page.locator('#play-button').getAttribute('aria-label'),'Pause score');await page.locator('#stop-button').click();await page.locator('#metronome-button').click();await page.locator('#metro-start').click();await page.waitForFunction(()=>document.querySelector('#metro-beats i.current'));await page.locator('#metro-start').click();await page.getByRole('button',{name:'Close metronome',exact:true}).click();await page.locator('#monitor-button').click();await page.locator('#monitor-demo').click();await page.getByRole('button',{name:'Stop monitoring',exact:true}).waitFor();await page.getByRole('button',{name:'Close voice monitor',exact:true}).click();
 await page.locator('#reading-position').click();await page.locator('#select-none').click();for(const n of [1,3])await page.getByRole('button',{name:`Include page ${n}`,exact:true}).click();await page.locator('#import-continue').click();await page.waitForFunction(()=>document.querySelector('#page-count').textContent.includes('/ 2'));await ready();let record=await page.evaluate(async()=>{const {library}=await import('./storage.js');const s=(await library.get('morning-practice')).score;return {pages:[...new Set(s.events.map(n=>n.page))],duration:s.duration,errors:s.events.filter(n=>!s.measures.some(m=>m.number===n.measure&&Math.abs(n.time-m.start-n.beat)<1e-6)).length};});assert.deepEqual(record,{pages:[0,2],duration:32,errors:0});await page.locator('#reading-position').click();await page.locator('#select-all').click();await page.locator('#import-continue').click();await ready();assert.match(await page.locator('#reading-position').textContent(),/of 4/);
 await page.locator('#review-button').click();await page.locator('#review-page canvas[data-ready=true]').waitFor();await page.getByRole('button',{name:/^Review Soprano/}).first().press('Enter');await page.locator('#review-part-name').fill('Soprano saved');await page.locator('#apply-correction').click();await page.waitForFunction(()=>document.querySelector('#review-summary').textContent==='Correction saved on this device.');await page.locator('#finish-review').click();await page.reload();await ready();await page.locator('#monitor-button').click();assert.match(await page.locator('#monitor-part option[value="P1"]').textContent(),/Soprano saved/);await page.getByRole('button',{name:'Close voice monitor',exact:true}).click();
 await page.setViewportSize({width:820,height:1180});await page.waitForTimeout(200);await ready();assert.equal(await page.locator('.score-sheet').count(),1);await page.screenshot({path:'screenshots/public-portrait.png'});
 const config=await (await page.request.get(new URL('assets/app-config.json',url).href)).json();if(config.recognitionAvailable){assert.deepEqual(errors,[]);assert.deepEqual(api,[]);console.log('PASS: hosted demo, orientations/page turns, linked parts/rhythm, Web Audio/metronome/synthetic microphone, page filtering/reinclusion and persisted corrections. Real hosted PDF recognition is checked separately by cloud-browser.cjs.');return;}
 const pdf=await page.request.get(new URL('assets/morning-practice.pdf',url).href);await page.locator('#pdf-file').setInputFiles({name:'my-score.pdf',mimeType:'application/pdf',buffer:await pdf.body()});await page.locator('#import-dialog[open]').waitFor();assert.match(await page.locator('#import-instruction').textContent(),/requires the local version/);await page.locator('#select-none').click();await page.getByRole('button',{name:'Include page 2',exact:true}).click();await page.locator('#import-continue').click();await page.waitForFunction(()=>document.querySelector('.score-sheet')?.dataset.page==='1'&&document.querySelector('#score-title').textContent==='my-score');await ready();assert.equal(await page.locator('.score-sheet').first().getAttribute('data-page'),'1');assert.equal(await page.locator('[data-note]').count(),0);assert.match(await page.locator('#score-status').textContent(),/viewing only/);await page.reload();await ready();assert.equal(await page.locator('#score-title').textContent(),'my-score');assert.deepEqual(api,[]);assert.deepEqual(errors,[]);
 console.log('PASS: Pages project subpath; original demo; orientations/page turns; linked parts/rhythm; Web Audio/metronome/synthetic microphone; page filtering and reinclusion; corrections/reload; PDF-only selected-page upload/save without server requests.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
